[package]
name = "gears-gui"
version.workspace = true
edition.workspace = true

[dependencies]
winit = { workspace = true }
wgpu = { workspace = true }
egui = { workspace = true }
egui-wgpu = { workspace = true }
egui-winit = { workspace = true }
